root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -tags dev -o ./tmp/ask-howard ./cmd/server"
  entrypoint = "./tmp/ask-howard"
  include_ext = ["go"]
  exclude_dir = ["web", "tmp", "internal/testutil", "internal/adapter/outbound/postgres/migrations"]
  delay = 500

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
