// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentSet = `-- name: CreateDocumentSet :one
INSERT INTO document_sets (user_id, original_filename, status, object_key)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, original_filename, status, object_key, error, created_at, updated_at
`

type CreateDocumentSetParams struct {
	UserID           uuid.UUID
	OriginalFilename string
	Status           string
	ObjectKey        string
}

func (q *Queries) CreateDocumentSet(ctx context.Context, arg CreateDocumentSetParams) (DocumentSet, error) {
	row := q.db.QueryRow(ctx, createDocumentSet,
		arg.UserID,
		arg.OriginalFilename,
		arg.Status,
		arg.ObjectKey,
	)
	var i DocumentSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalFilename,
		&i.Status,
		&i.ObjectKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentSetByIDAndUser = `-- name: GetDocumentSetByIDAndUser :one
SELECT id, user_id, original_filename, status, object_key, error, created_at, updated_at FROM document_sets
WHERE id = $1 AND user_id = $2
`

type GetDocumentSetByIDAndUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDocumentSetByIDAndUser(ctx context.Context, arg GetDocumentSetByIDAndUserParams) (DocumentSet, error) {
	row := q.db.QueryRow(ctx, getDocumentSetByIDAndUser, arg.ID, arg.UserID)
	var i DocumentSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalFilename,
		&i.Status,
		&i.ObjectKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentSetStatus = `-- name: UpdateDocumentSetStatus :one
UPDATE document_sets
SET status = $1, error = $2, updated_at = now()
WHERE id = $3
RETURNING id, user_id, original_filename, status, object_key, error, created_at, updated_at
`

type UpdateDocumentSetStatusParams struct {
	Status string
	Error  pgtype.Text
	ID     uuid.UUID
}

func (q *Queries) UpdateDocumentSetStatus(ctx context.Context, arg UpdateDocumentSetStatusParams) (DocumentSet, error) {
	row := q.db.QueryRow(ctx, updateDocumentSetStatus, arg.Status, arg.Error, arg.ID)
	var i DocumentSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalFilename,
		&i.Status,
		&i.ObjectKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
