// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DocumentSet struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	OriginalFilename string
	Status           string
	ObjectKey        string
	Error            pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLoginAt  pgtype.Timestamptz
}
