// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID          uuid.UUID
	SetID       uuid.UUID
	UserID      uuid.UUID
	Filename    string
	ContentType string
	SizeBytes   int64
	ObjectKey   string
	CanvasX     pgtype.Float8
	CanvasY     pgtype.Float8
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DocumentSet struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	OriginalFilename string
	Status           string
	ObjectKey        string
	Error            pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLoginAt  pgtype.Timestamptz
}
